// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDJXe02nc2y825ZeebXct4MGeiGYJXphyA',
    appId: '1:589417482364:web:3c65a0a999fa7fec4421f9',
    messagingSenderId: '589417482364',
    projectId: 'logapp-11351',
    authDomain: 'logapp-11351.firebaseapp.com',
    storageBucket: 'logapp-11351.appspot.com',
    measurementId: 'G-BN27N390S9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD_TawCvU8mlKvVg2zt8nImuwjRH8pcA8I',
    appId: '1:589417482364:android:b23b6e1f50377d1d4421f9',
    messagingSenderId: '589417482364',
    projectId: 'logapp-11351',
    storageBucket: 'logapp-11351.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDLD-0b1yRfgYm-7heUiftYF-LDBKiCEwA',
    appId: '1:589417482364:ios:431173909d1bf2f24421f9',
    messagingSenderId: '589417482364',
    projectId: 'logapp-11351',
    storageBucket: 'logapp-11351.appspot.com',
    iosBundleId: 'com.example.logapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDLD-0b1yRfgYm-7heUiftYF-LDBKiCEwA',
    appId: '1:589417482364:ios:f654bc89a8fecad64421f9',
    messagingSenderId: '589417482364',
    projectId: 'logapp-11351',
    storageBucket: 'logapp-11351.appspot.com',
    iosBundleId: 'com.example.logapp.RunnerTests',
  );
}
